apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: keyval/kv-mall-analytics:v0.2
        env:
        - name: KAFKA_ADDRESS
          value: kafka-service:9092
        - name: MEMCACHED_ADDR
          value: memcached:11211
        - name: CASSANDRA_ADDR
          value: cassandra:9042
        - name: POSTGRESQL_ADDR
          value: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos
              key: COSMOS_KEY